<?php
/**
 * Created by PhpStorm.
 * User: xiemin
 * Date: 2015/11/10
 * Time: 19:09
 */

return array(
    'kafka' => array(
        'kafka_brokers' => array(
            '10.50.3.235',
            '10.50.3.236',
            '10.50.3.237'
        ),
        'log_level' => LOG_DEBUG,
        'zookeeper_host' => 'localhost',
        'zookeeper_port' => '2181'
    ),
    'mongo' => array(
        // 跨机房性能下降严重, insert最快， save稍慢， update最慢
        'mongourl' => 'mongodb://10.90.2.73:20000,10.90.2.74:20000,10.90.2.75:20000/', //600qps
//        'mongourl' => 'mongodb://10.90.2.73:22001/', //1000qps
//        'mongourl' => 'mongodb://10.50.3.117:10002/', //3000qps
//        'mongourl' => 'mongodb://localhost:27017/', //3000qps
        'option' => array('w' => 1),
        'db' => 'usercenter',
        'userbase' => 'userbase',
        'useraction' => 'useraction'
    ),
    'userinfo' => array(
        'alldata' => array(
            "date",
            "userkey",
            "login_time",
            "publish_id",
            "platform",
            "ua",
            "mos",
            "soft_version",
//            "ip",
            "net",
            "is_update",
            "is_dau",
            "first_access_time",
            "hb",
            "page_aids",
            "page_count",
            "page_view_count",
            "share_aids",
            "share_count",
            "pushaccess_aids",
            "pushaccess_count",
            "openpush_aids",
            "openpush_count",
            "push_action",
            "except",
            "except_count",
            "life_time",
            "in_action",
            "in_count",
            "login",
            "login_count",
            "actions",
//            "store",
//            "dispic",
//            "ngmode",
//            "follow",
//            "reply",
//            "support",
//            "share",
//            "survey",
//            "ngr",
//            "lv",
//            "chat",
//            "tfc",
//            "radio",
//            "cdr",
//            "ckup",
//            "fnch",
//            "pnp",
//            "ckcw",
//            "vdt",
//            "msub",
//            "fd",
//            "search",
//            "adjp",
//            "cdcr",
//            "opwf",
//            "ad",
//            "atoast",
//            "ctoast",
//            "srhmo",
//            "editch",
//            "cpurl",
//            "sharemo",
//            "update",
//            "chmg",
//            "cache",
//            "chmark",
//            "keywd",
//            "cdrtt",
//            "fmdload",
//            "fmwin"
        ),
        'userbase' => array(
            "date" => null,
            "userkey" => null,
            "login_time" => null,
            "publish_id" => null,
            "platform" => null,
            "ua" => null,
            "mos" => null,
            "soft_version" => null,
//            "ip" => null,
            "net" => null,
        ),
        'useraction' => array(
            "userkey" => null,
            "is_dau" => null,
            "first_access_time" => null,
            "hb" => null,
            "page_aids" => null,
            "page_count" => null,
            "page_view_count" => null,
            "share_aids" => null,
            "share_count" => null,
            "pushaccess_aids" => null,
            "pushaccess_count" => null,
            "openpush_aids" => null,
            "openpush_count" => null,
            "push_action" => null,
            "except" => null,
            "except_count" => null,
            "life_time" => null,
            "in_action" => null,
            "in_count" => null,
            "login" => null,//todo
            "login_count" => null,
            "actions_count" => null,
            "actions" => null,
//            "store" => null,
//            "dispic" => null,
//            "ngmode" => null,
//            "follow" => null,
//            "reply" => null,
//            "support" => null,
//            "share" => null,
//            "survey" => null,
//            "ngr" => null,
//            "lv" => null,
//            "chat" => null,
//            "tfc" => null,
//            "radio" => null,
//            "cdr" => null,
//            "ckup" => null,
//            "fnch" => null,
//            "pnp" => null,
//            "ckcw" => null,
//            "vdt" => null,
//            "msub" => null,
//            "fd" => null,
//            "search" => null,
//            "adjp" => null,
//            "cdcr" => null,
//            "opwf" => null,
//            "ad" => null,
//            "atoast" => null,
//            "ctoast" => null,
//            "srhmo" => null,
//            "editch" => null,
//            "cpurl" => null,
//            "sharemo" => null,
//            "update" => null,
//            "chmg" => null,
//            "cache" => null,
//            "chmark" => null,
//            "keywd" => null,
//            "cdrtt" => null,
//            "fmdload" => null,
//            "fmwin"
        )
    )
);